/**
 * Writes src/database/drizzle/schema.generated.ts — a typed Drizzle view of
 * the tables in the registry, for typed SQL, reporting and drizzle-kit.
 */
const fs = require("fs");
const path = require("path");
const { BACKEND_DIR } = require("./lib");

const camel = (s) => s.replace(/[^A-Za-z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[A-Z]/, (c) => c.toLowerCase());

function drizzleCol(c) {
  const n = JSON.stringify(c.column);
  switch (c.kind) {
    case "objectId":
    case "string":
      return `text(${n})`;
    case "number":
      return `doublePrecision(${n})`;
    case "date":
      return `timestamp(${n}, { withTimezone: true, mode: "date" })`;
    case "boolean":
      return `boolean(${n})`;
    case "objectId[]":
    case "string[]":
      return `text(${n}).array()`;
    case "number[]":
      return `doublePrecision(${n}).array()`;
    case "date[]":
      return `timestamp(${n}, { withTimezone: true, mode: "date" }).array()`;
    case "boolean[]":
      return `boolean(${n}).array()`;
    default:
      return `jsonb(${n})`;
  }
}

function writeDrizzle(registry) {
  const schemas = [...new Set(registry.tables.map((t) => t.schema))];
  const exportNames = new Set();
  const ts = [
    "/* eslint-disable */",
    "// GENERATED by database/generate.js — do not edit by hand.",
    "// Typed Drizzle view of the Supabase tables. The API reaches them through the",
    "// Mongoose models and the Postgres driver (src/database/pg). Values that did not",
    "// fit a column type are in `_extra`; explicit nulls are listed in `_nulls`.",
    'import { boolean, doublePrecision, jsonb, pgSchema, pgTable, text, timestamp } from "drizzle-orm/pg-core";',
    "",
    ...schemas.filter((s) => s !== "public").map((s) => `export const ${camel(s)}Schema = pgSchema(${JSON.stringify(s)});`),
    "",
  ];
  for (const t of registry.tables) {
    let name = camel(t.schema === "public" ? t.table : `${t.schema}_${t.table}`);
    if (/^[0-9]/.test(name)) name = `t${name}`;
    while (exportNames.has(name)) name += "_";
    exportNames.add(name);
    const factory = t.schema === "public" ? "pgTable" : `${camel(t.schema)}Schema.table`;
    const fields = [`  id: text("id").primaryKey(), // model: _id`];
    const usedKeys = new Set(["id", "_nulls", "_extra"]);
    for (const c of t.columns) {
      let key = camel(c.column) || "field";
      while (usedKeys.has(key)) key += "_";
      usedKeys.add(key);
      fields.push(`  ${JSON.stringify(key)}: ${drizzleCol(c)}, // model: ${c.field}`);
    }
    fields.push(`  _nulls: text("_nulls").array(),`, `  _extra: jsonb("_extra"),`);
    ts.push(`/** ${t.schema}.${t.table} */`, `export const ${name} = ${factory}(${JSON.stringify(t.table)}, {\n${fields.join("\n")}\n});`, "");
  }
  const dir = path.join(BACKEND_DIR, "src/database/drizzle");
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "schema.generated.ts"), ts.join("\n"));
}

module.exports = { writeDrizzle };
