-- Generated by npm run db:generate on 2026-10-08T06:09:12.123Z
--   public.booking_bookings: +0 column(s), +1 index(es) (customerId_1)

CREATE INDEX IF NOT EXISTS "booking_bookings_ix_435dc7a5" ON "public"."booking_bookings" USING btree ("customer_id");
